outpath <- find_testthat_root_file("out/error-msgs.txt")

test_that("error messages do not change", {
  verify_output(outpath, {
    error_txt_wrong_col_args()
    error_txt_key_set_force_false()
    error_txt_not_unique_key("Christmas", c("elves", "Rudolph", "mulled_wine"))
    error_txt_table_not_in_dm(c("laziness", "daydreaming"), c("hard_work", "focus", "overhours"))
    error_txt_not_subset_of("playing", "game", "hunting", "game")
    error_txt_sets_not_equal(c("A problem occurred", "And another, even worse problem, occurred shortly after"))
    # The mentioned reasons for not being bijective and injective are the same, but this is intended:
    # If surjectivity is not given during the test for bijectivity it will fail earlier
    error_txt_not_bijective("child_table_name", "fk_col_name")
    error_txt_not_injective("child_table_name", "fk_col_name")
    error_txt_ref_tbl_has_no_pk("parent_table")
    error_txt_is_not_fk("child_table_name", c("wrong_fk_colname", "and_one_more"), "parent_table_name", c("actual_fk_colname", "and_one_more"))
    error_txt_rm_fk_col_missing()
    error_txt_last_col_missing()
    error_txt_wrong_color()
    error_txt_no_cycles()
    error_txt_tables_not_reachable_from_start()
    error_txt_wrong_col_names("table_name", c("col_1", "col_2"), c("col_one", "col_2"))
    error_txt_wrong_col_names("table_name", c("col_1", "col_2"), "col_one")
    error_txt_dupl_new_id_col_name("tibbletable")
    error_txt_no_overwrite("fun")
    error_txt_no_types()
    error_txt_no_indexes()
    error_txt_no_unique_indexes()
    error_txt_need_named_vec(c("activity", "income", "expenses", "loss_or_gain"))
    error_src_not_db()
    error_first_rm_fks("parent", c("child_1", "child_2"))
    error_no_src_or_con()
    error_update_not_supported()
    error_only_possible_wo_filters("find_wisdom")
    error_tables_not_neighbours("subjects", "king")
    error_only_parents()
    error_not_same_src()
    error_what_a_weird_object("monster")
    error_not_same_src()
    error_squash_limited()
    error_apply_filters_first("join_tightly")
    error_no_flatten_with_nest_join()
    error_unique_table_names_or_table_names()
    error_is_not_dm("blob")
    error_con_only_for_dbi()
    error_no_zoom_allowed()
    error_no_table_zoomed()
    error_table_needs_name()
    error_only_possible_wo_zoom("dm_zoom_to_tbl")
    error_only_possible_w_zoom("dm_update_zoomed_tbl")
    error_req_tbl_not_avail(c("dull", "boring", "common_knowledge"), c("fascinating", "interesting"))
    error_unnamed_table_list()
    error_need_unique_names("clone")
    error_fk_not_tracked("hook", "eye")
    error_need_to_select_rhs_by("RHS", "by")
    error_dm_invalid("it's ugly")
    error_no_table_provided()
    error_table_not_zoomed("blur", c("focus_1", "focus_2"))
    error_not_pulling_multiple_zoomed()
    error_cols_not_avail(c("pink5", "elephant"))
    error_only_named_args("give_names", "important")
  })
})
