outpath <- find_testthat_root_file("out/error-msgs.txt")

test_that("error messages do not change", {
  verify_output(outpath, {
    abort_key_set_force_false("pk_table")
    abort_not_unique_key("Christmas", "Rudolph")
    abort_not_unique_key("Christmas", c("elves", "Rudolph", "mulled_wine"))
    abort_table_not_in_dm("laziness", "hard_work")
    abort_table_not_in_dm(c("laziness", "daydreaming"), c("hard_work", "focus", "overtime"))
    abort_not_subset_of("playing", "game", "hunting", "game")
    abort_sets_not_equal(c("A problem occurred", "And another, even worse problem, occurred shortly after"))
    # The mentioned reasons for not being bijective and injective are the same, but this is intended:
    # If surjectivity is not given during the test for bijectivity it will fail earlier
    abort_not_bijective("child_table_name", "fk_col_name")
    abort_not_injective("child_table_name", "fk_col_name")
    abort_ref_tbl_has_no_pk("parent_table")
    abort_is_not_fk("child_table_name", c("wrong_fk_colname", "and_one_more"), "parent_table_name", c("actual_fk_colname", "and_one_more"))
    abort_rm_fk_col_missing()
    abort_last_col_missing()
    abort_no_cycles()
    abort_tables_not_reachable_from_start()
    abort_wrong_col_names("table_name", c("col_1", "col_2"), c("col_one", "col_2"))
    abort_wrong_col_names("table_name", c("col_1", "col_2"), "col_one")
    abort_dupl_new_id_col_name("tibbletable")
    abort_no_overwrite("fun")
    abort_no_types()
    abort_no_indexes()
    abort_no_unique_indexes()
    abort_need_named_vec(c("activity", "income", "expenses", "loss_or_gain"))
    error_txt_src_not_db()
    error_txt_first_rm_fks("parent", c("child_1", "child_2"))
    error_txt_no_src_or_con()
    error_txt_update_not_supported()
    error_txt_only_possible_wo_filters("find_wisdom")
    error_txt_tables_not_neighbours("subjects", "king")
    error_txt_only_parents()
    error_txt_not_same_src()
    error_txt_what_a_weird_object("monster")
    error_txt_not_same_src()
    error_txt_squash_limited()
    error_txt_apply_filters_first("join_tightly")
    error_txt_no_flatten_with_nest_join()
    error_txt_unique_table_names_or_table_names()
    error_txt_is_not_dm("blob")
    error_txt_con_only_for_dbi()
    error_txt_table_needs_name()
    error_txt_only_possible_wo_zoom("dm_zoom_to")
    error_txt_only_possible_w_zoom("dm_update_zoomed")
    error_txt_req_tbl_not_avail(c("dull", "boring", "common_knowledge"), c("fascinating", "interesting"))
    error_txt_unnamed_table_list()
    error_txt_need_unique_names("clone")
    error_txt_fk_not_tracked("hook", "eye")
    error_txt_need_to_select_rhs_by("RHS", "by")
    error_txt_dm_invalid("it's ugly")
    error_txt_no_table_provided()
    error_txt_table_not_zoomed("blur", c("focus_1", "focus_2"))
    error_txt_not_pulling_multiple_zoomed()
    error_txt_cols_not_avail(c("pink5", "elephant"))
    error_txt_only_named_args("give_names", "important")
    error_txt_wrong_syntax_set_cols()
    error_txt_temp_table_requested(c("i_am_temporary", "i_am_permanent"), "i_am_permanent")
  })
})
