<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Introduction to relational data models • dm</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Introduction to relational data models">
<meta property="og:description" content="dm">
<meta property="og:image" content="https://krlmlr.github.io/dm/logo.png">
<meta name="robots" content="noindex">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    

    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">dm</a>
        <span class="version label label-danger" data-toggle="tooltip" data-placement="bottom" title="In-development version">0.1.12.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../articles/dm.html">Intro</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Tutorials
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/howto-dm-theory.html">Introduction to relational data models</a>
    </li>
    <li>
      <a href="../articles/howto-dm-df.html">Create a dm object from data frames</a>
    </li>
    <li>
      <a href="../articles/howto-dm-db.html">Create a dm object from a database</a>
    </li>
    <li>
      <a href="../articles/howto-dm-copy.html">Copy data to and from a database</a>
    </li>
    <li>
      <a href="../articles/howto-dm-rows.html">Insert, update or remove rows in a database</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Technical articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/tech-dm-join.html">Joining in relational data models</a>
    </li>
    <li>
      <a href="../articles/tech-dm-zoom.html">Zooming and manipulating tables</a>
    </li>
    <li>
      <a href="../articles/tech-dm-filter.html">Filtering in relational data models</a>
    </li>
    <li>
      <a href="../articles/tech-dm-draw.html">Visualizing dm objects</a>
    </li>
    <li>
      <a href="../articles/tech-dm-low-level.html">Model verification - keys, constraints and normalization</a>
    </li>
    <li>
      <a href="../articles/tech-dm-class.html">Class 'dm' and basic operations</a>
    </li>
    <li>
      <a href="../articles/tech-dm-naming.html">Function naming logic</a>
    </li>
    <li>
      <a href="../articles/tech-dm-cdm.html">Migration guide: 'cdm' -&gt; 'dm'</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/krlmlr/dm" class="external-link">
    <span class="fas fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="howto-dm-theory_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Introduction to relational data models</h1>
                        <h4 data-toc-skip class="author">Katharina Brunner</h4>
            
            <h4 data-toc-skip class="date">2021-04-25</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/krlmlr/dm/blob/master/vignettes/howto-dm-theory.Rmd" class="external-link"><code>vignettes/howto-dm-theory.Rmd</code></a></small>
      <div class="hidden name"><code>howto-dm-theory.Rmd</code></div>

    </div>

    
    
<p>Multiple, linked tables are common within computer science. Because many R users have backgrounds in other disciplines, we present <strong>six important terms in relational data modeling</strong> to help you to jump-start working with {dm}. These terms are:</p>
<ol style="list-style-type: decimal">
<li><a href="#tables">Data Frames and Tables</a></li>
<li><a href="#model">Data Model</a></li>
<li><a href="#pk">Primary Keys</a></li>
<li><a href="#fk">Foreign Keys</a></li>
<li><a href="#referential-integrity">Referential Integrity</a></li>
<li><a href="#normalization">Normalization</a></li>
<li><a href="#relational-databases">Relational Databases</a></li>
</ol>
<div id="data-frames-and-tables" class="section level2">
<h2 class="hasAnchor">
<a href="#data-frames-and-tables" class="anchor" aria-hidden="true"></a>1. Data Frames and Tables</h2>
<p>A data frame is a fundamental data structure in R. Columns represent variables, rows represent observations. In more technical terms: a data frame is a list of variables of identical length and unique row names. If you imagine it visually, the result is a typical table structure. That is why working with data from spreadsheets is so convenient and the users of the popular <a href="https://dplyr.tidyverse.org" class="external-link">{dplyr}</a> package for data wrangling mainly rely on data frames.</p>
<p>The downside is that data frames and flat file systems like spreadsheets can result in bloated tables because they hold many repetitive values. In the worst case, a data frame can contain multiple columns with only a single value different in each row.</p>
<p>This calls for better data organization by utilizing the resemblance between data frames and database tables, which also consist of columns and rows. The elements are just named differently:</p>
<table class="table">
<thead><tr class="header">
<th>Data Frame</th>
<th>Table</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Column</td>
<td>Attribute</td>
</tr>
<tr class="even">
<td>Row</td>
<td>Tuple</td>
</tr>
</tbody>
</table>
<p>Relational databases, unlike data frames, do not keep all data in one large table but instead split it into multiple smaller tables. That separation into sub-tables has several advantages:</p>
<ul>
<li>all information is stored only once, avoiding redundancy and conserving memory</li>
<li>all information needs to be updated only once and in one place, improving consistency and avoiding errors that may result from updating the same value in multiple locations</li>
<li>all information is organized by topic and segmented into smaller tables that are easier to handle</li>
</ul>
<p>It is for these reasons that separation of data helps with data quality, and they explain the popularity of relational databases in production-level data management.</p>
<p>The downside of this approach is that it is harder to merge together information from different data sources and to identify which entities refer to the same object, a common task when modeling or plotting data.</p>
<p>Thus, to take full advantage of the relational database approach, an associated data model is needed to overcome the challenges that arise when working with multiple tables.</p>
<p>Let’s illustrate this challenge with the data from the <a href="https://github.com/hadley/nycflights13" class="external-link"><code>nycflights13</code> dataset</a> that contains detailed information about the 336776 flights that departed from New York City in 2013. The information is stored in five tables.</p>
<p>Details like the full name of an airport are not available immediately; these can only be obtained by joining or merging the constituent tables, which can result in long and inflated pipe chains full of <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">left_join()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/filter-joins.html" class="external-link">anti_join()</a></code> and other forms of data merging.</p>
<p>In classical {dplyr} notation, you will need three <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">left_join()</a></code> calls to merge the <code>flights</code> table gradually to <code>airlines</code>, <code>planes</code> and <code>airports</code> tables to create one wide data frame.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org" class="external-link">tidyverse</a></span><span class="op">)</span></code></pre></div>
<pre class="fansi fansi-message"><code>#&gt; ── <span style="font-weight: bold;">Attaching packages</span><span> ────────────────────────────────── tidyverse 1.3.1 ──
</span></code></pre>
<pre class="fansi fansi-message"><code>#&gt; <span style="color: #00BB00;">✔</span><span> </span><span style="color: #0000BB;">ggplot2</span><span> 3.3.3     </span><span style="color: #00BB00;">✔</span><span> </span><span style="color: #0000BB;">purrr  </span><span> 0.3.4
#&gt; </span><span style="color: #00BB00;">✔</span><span> </span><span style="color: #0000BB;">tibble </span><span> 3.1.1     </span><span style="color: #00BB00;">✔</span><span> </span><span style="color: #0000BB;">dplyr  </span><span> 1.0.5
#&gt; </span><span style="color: #00BB00;">✔</span><span> </span><span style="color: #0000BB;">tidyr  </span><span> 1.1.3     </span><span style="color: #00BB00;">✔</span><span> </span><span style="color: #0000BB;">stringr</span><span> 1.4.0
#&gt; </span><span style="color: #00BB00;">✔</span><span> </span><span style="color: #0000BB;">readr  </span><span> 1.4.0     </span><span style="color: #00BB00;">✔</span><span> </span><span style="color: #0000BB;">forcats</span><span> 0.5.1
</span></code></pre>
<pre class="fansi fansi-message"><code>#&gt; ── <span style="font-weight: bold;">Conflicts</span><span> ───────────────────────────────────── tidyverse_conflicts() ──
#&gt; </span><span style="color: #BB0000;">✖</span><span> </span><span style="color: #0000BB;">dplyr</span><span>::</span><span style="color: #00BB00;">filter()</span><span> masks </span><span style="color: #0000BB;">dm</span><span>::filter(), </span><span style="color: #0000BB;">stats</span><span>::filter()
#&gt; </span><span style="color: #BB0000;">✖</span><span> </span><span style="color: #0000BB;">dplyr</span><span>::</span><span style="color: #00BB00;">lag()</span><span>    masks </span><span style="color: #0000BB;">stats</span><span>::lag()
</span></code></pre>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://krlmlr.github.io/dm/">dm</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/hadley/nycflights13" class="external-link">nycflights13</a></span><span class="op">)</span>

<span class="va">flights</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">left_join</a></span><span class="op">(</span><span class="va">airlines</span>, by <span class="op">=</span> <span class="st">"carrier"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">left_join</a></span><span class="op">(</span><span class="va">planes</span>, by <span class="op">=</span> <span class="st">"tailnum"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">left_join</a></span><span class="op">(</span><span class="va">airports</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"origin"</span> <span class="op">=</span> <span class="st">"faa"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre class="fansi fansi-output"><code>#&gt; <span style="color: #555555;"># A tibble: 336,776 x 35</span><span>
#&gt;    year.x month   day dep_time sched_dep_time dep_delay arr_time
#&gt;     </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span>    </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span>          </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span>     </span><span style="color: #555555;font-style: italic;">&lt;dbl&gt;</span><span>    </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span>
#&gt; </span><span style="color: #555555;"> 1</span><span>   </span><span style="text-decoration: underline;">2</span><span>013     1     1      517            515         2      830
#&gt; </span><span style="color: #555555;"> 2</span><span>   </span><span style="text-decoration: underline;">2</span><span>013     1     1      533            529         4      850
#&gt; </span><span style="color: #555555;"> 3</span><span>   </span><span style="text-decoration: underline;">2</span><span>013     1     1      542            540         2      923
#&gt; </span><span style="color: #555555;"> 4</span><span>   </span><span style="text-decoration: underline;">2</span><span>013     1     1      544            545        -</span><span style="color: #BB0000;">1</span><span>     </span><span style="text-decoration: underline;">1</span><span>004
#&gt; </span><span style="color: #555555;"> 5</span><span>   </span><span style="text-decoration: underline;">2</span><span>013     1     1      554            600        -</span><span style="color: #BB0000;">6</span><span>      812
#&gt; </span><span style="color: #555555;"> 6</span><span>   </span><span style="text-decoration: underline;">2</span><span>013     1     1      554            558        -</span><span style="color: #BB0000;">4</span><span>      740
#&gt; </span><span style="color: #555555;"> 7</span><span>   </span><span style="text-decoration: underline;">2</span><span>013     1     1      555            600        -</span><span style="color: #BB0000;">5</span><span>      913
#&gt; </span><span style="color: #555555;"> 8</span><span>   </span><span style="text-decoration: underline;">2</span><span>013     1     1      557            600        -</span><span style="color: #BB0000;">3</span><span>      709
#&gt; </span><span style="color: #555555;"> 9</span><span>   </span><span style="text-decoration: underline;">2</span><span>013     1     1      557            600        -</span><span style="color: #BB0000;">3</span><span>      838
#&gt; </span><span style="color: #555555;">10</span><span>   </span><span style="text-decoration: underline;">2</span><span>013     1     1      558            600        -</span><span style="color: #BB0000;">2</span><span>      753
#&gt; </span><span style="color: #555555;"># … with 336,766 more rows, and 28 more variables: sched_arr_time &lt;int&gt;,</span><span>
#&gt; </span><span style="color: #555555;">#   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,</span><span>
#&gt; </span><span style="color: #555555;">#   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,</span><span>
#&gt; </span><span style="color: #555555;">#   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;, name.x &lt;chr&gt;, year.y &lt;int&gt;,</span><span>
#&gt; </span><span style="color: #555555;">#   type &lt;chr&gt;, manufacturer &lt;chr&gt;, model &lt;chr&gt;, engines &lt;int&gt;,</span><span>
#&gt; </span><span style="color: #555555;">#   seats &lt;int&gt;, speed &lt;int&gt;, engine &lt;chr&gt;, name.y &lt;chr&gt;, lat &lt;dbl&gt;,</span><span>
#&gt; </span><span style="color: #555555;">#   lon &lt;dbl&gt;, alt &lt;dbl&gt;, tz &lt;dbl&gt;, dst &lt;chr&gt;, tzone &lt;chr&gt;</span><span>
</span></code></pre>
<p>{dm} offers a more elegant and shorter way to combine tables while augmenting {dplyr}/{dbplyr} workflows.</p>
<p>It is possible to have the best of both worlds: manage your data with {dm} as linked tables, then flatten multiple tables into one for your analysis with {dplyr} on an as-needed basis.</p>
<p>The next step is to create a <a href="#model">data model</a> based on multiple tables:</p>
</div>
<div id="model" class="section level2">
<h2 class="hasAnchor">
<a href="#model" class="anchor" aria-hidden="true"></a>2. Data Model</h2>
<p>A data model shows the structure between multiple tables that can be linked together.</p>
<p>The <code>nycflights13</code> relations can be transferred into the following graphical representation:</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dm</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/dm_nycflights13.html">dm_nycflights13</a></span><span class="op">(</span>cycle <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>

<span class="va">dm</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="../reference/dm_draw.html">dm_draw</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Generated by graphviz version 2.40.1 (20161225.0304)
 --><!-- Title: %0 Pages: 1 --><svg width="153pt" height="187pt" viewbox="0.00 0.00 153.00 187.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 183)"><title>%0</title>
<g id="a_graph0"><a xlink:title="Data Model">
<polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-183 149,-183 149,4 -4,4"></polygon></a>
</g><!-- airlines --><g id="node1" class="node"><title>airlines</title>
<polygon fill="#ed7d31" stroke="transparent" points="96,-141 96,-161 141,-161 141,-141 96,-141"></polygon><text text-anchor="start" x="97.8969" y="-146.4" font-family="Times,serif" font-size="14.00" fill="#ffffff">airlines</text><polygon fill="#fbe5d5" stroke="transparent" points="96,-121 96,-141 141,-141 141,-121 96,-121"></polygon><text text-anchor="start" x="98" y="-127.4" font-family="Times,serif" text-decoration="underline" font-size="14.00" fill="#444444">carrier</text><polygon fill="none" stroke="#9e5320" stroke-opacity="0.666667" points="94.5,-120 94.5,-162 141.5,-162 141.5,-120 94.5,-120"></polygon></g><!-- airports --><g id="node2" class="node"><title>airports</title>
<polygon fill="#ed7d31" stroke="transparent" points="95,-21 95,-41 141,-41 141,-21 95,-21"></polygon><text text-anchor="start" x="96.6192" y="-26.4" font-family="Times,serif" font-size="14.00" fill="#ffffff">airports</text><polygon fill="#fbe5d5" stroke="transparent" points="95,-1 95,-21 141,-21 141,-1 95,-1"></polygon><text text-anchor="start" x="97" y="-7.4" font-family="Times,serif" text-decoration="underline" font-size="14.00" fill="#444444">faa</text><polygon fill="none" stroke="#9e5320" stroke-opacity="0.666667" points="94,0 94,-42 142,-42 142,0 94,0"></polygon></g><!-- flights --><g id="node3" class="node"><title>flights</title>
<polygon fill="#5b9bd5" stroke="transparent" points="5,-91 5,-111 51,-111 51,-91 5,-91"></polygon><text text-anchor="start" x="10.1115" y="-96.4" font-family="Times,serif" font-size="14.00" fill="#ffffff">flights</text><polygon fill="#deebf6" stroke="transparent" points="5,-71 5,-91 51,-91 51,-71 5,-71"></polygon><text text-anchor="start" x="7" y="-76.4" font-family="Times,serif" font-size="14.00" fill="#444444">carrier</text><polygon fill="#deebf6" stroke="transparent" points="5,-51 5,-71 51,-71 51,-51 5,-51"></polygon><text text-anchor="start" x="6.6115" y="-56.4" font-family="Times,serif" font-size="14.00" fill="#444444">tailnum</text><polygon fill="#deebf6" stroke="transparent" points="5,-31 5,-51 51,-51 51,-31 5,-31"></polygon><text text-anchor="start" x="7" y="-36.4" font-family="Times,serif" font-size="14.00" fill="#444444">origin</text><polygon fill="#deebf6" stroke="transparent" points="5,-11 5,-31 51,-31 51,-11 5,-11"></polygon><text text-anchor="start" x="7" y="-16.4" font-family="Times,serif" font-size="14.00" fill="#444444">dest</text><polygon fill="none" stroke="#3c678e" stroke-opacity="0.666667" points="4,-10 4,-112 52,-112 52,-10 4,-10"></polygon></g><!-- flights&#45;&gt;airlines --><g id="edge1" class="edge"><title>flights:carrier-&gt;airlines:carrier</title>
<path fill="none" stroke="#555555" d="M51,-81C76.9263,-81 69.2444,-118.6007 86.2435,-128.5884"></path><polygon fill="#555555" stroke="#555555" points="85.4523,-131.9981 96,-131 87.132,-125.2026 85.4523,-131.9981"></polygon></g><!-- flights&#45;&gt;airports --><g id="edge2" class="edge"><title>flights:origin-&gt;airports:faa</title>
<path fill="none" stroke="#555555" d="M51,-41C70.6005,-41 71.6808,-20.4263 84.915,-13.354"></path><polygon fill="#555555" stroke="#555555" points="86.0574,-16.6816 95,-11 84.4662,-9.8648 86.0574,-16.6816"></polygon></g><!-- flights&#45;&gt;airports --><g id="edge3" class="edge"><title>flights:dest-&gt;airports:faa</title>
<path fill="none" stroke="#555555" d="M51,-21C67.1374,-21 72.8091,-14.5248 84.8583,-11.9954"></path><polygon fill="#555555" stroke="#555555" points="85.3897,-15.4601 95,-11 84.7059,-8.4936 85.3897,-15.4601"></polygon></g><!-- planes --><g id="node4" class="node"><title>planes</title>
<polygon fill="#ed7d31" stroke="transparent" points="95,-81 95,-101 141,-101 141,-81 95,-81"></polygon><text text-anchor="start" x="100.1178" y="-86.4" font-family="Times,serif" font-size="14.00" fill="#ffffff">planes</text><polygon fill="#fbe5d5" stroke="transparent" points="95,-61 95,-81 141,-81 141,-61 95,-61"></polygon><text text-anchor="start" x="96.6115" y="-67.4" font-family="Times,serif" text-decoration="underline" font-size="14.00" fill="#444444">tailnum</text><polygon fill="none" stroke="#9e5320" stroke-opacity="0.666667" points="94,-60 94,-102 142,-102 142,-60 94,-60"></polygon></g><!-- flights&#45;&gt;planes --><g id="edge4" class="edge"><title>flights:tailnum-&gt;planes:tailnum</title>
<path fill="none" stroke="#555555" d="M51,-61C67.1374,-61 72.8091,-67.4752 84.8583,-70.0046"></path><polygon fill="#555555" stroke="#555555" points="84.7059,-73.5064 95,-71 85.3897,-66.5399 84.7059,-73.5064"></polygon></g><!-- weather --><g id="node5" class="node"><title>weather</title>
<polygon fill="#70ad47" stroke="transparent" points="3,-151 3,-171 51,-171 51,-151 3,-151"></polygon><text text-anchor="start" x="4.8492" y="-156.4" font-family="Times,serif" font-size="14.00" fill="#ffffff">weather</text><polygon fill="none" stroke="#4a732f" stroke-opacity="0.666667" points="2,-150 2,-172 52,-172 52,-150 2,-150"></polygon></g></g></svg><p>The <code>flights</code> table is linked to three other tables: <code>airlines</code>, <code>planes</code> and <code>airports</code>. By using directed arrows, the visualization shows explicitly the connection between different columns (they are called attributes in the relational data sphere).</p>
<p>For example: The column <code>carrier</code> in <code>flights</code> can be joined with the column <code>carrier</code> from the <code>airlines</code> table.</p>
<p>The links between the tables are established through <a href="#pk">primary keys</a> and <a href="#fk">foreign keys</a>.</p>
<p>Further Reading: The {dm} methods for <a href="https://krlmlr.github.io/dm/articles/tech-dm-draw.html">visualizing data models</a>.</p>
</div>
<div id="pk" class="section level2">
<h2 class="hasAnchor">
<a href="#pk" class="anchor" aria-hidden="true"></a>3. Primary Keys</h2>
<p>In a relational data model, every table needs to have <strong>one column or attribute that uniquely identifies a row</strong>. This column is called the <em>primary key</em> (abbreviated with pk). A primary key can be either an existing column that satisfies the condition of being unique, or a new column that assigns an identifier.</p>
<p>Example: In the <code>airlines</code> table of <code>nycflights13</code> the column <code>carrier</code> is the primary key.</p>
<p>You can get all primary keys in a <code>dm</code> by calling <code><a href="../reference/dm_get_all_pks.html">dm_get_all_pks()</a></code>:</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dm</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="../reference/dm_get_all_pks.html">dm_get_all_pks</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre class="fansi fansi-output"><code>#&gt; <span style="color: #555555;"># A tibble: 3 x 2</span><span>
#&gt;   table    pk_col 
#&gt;   </span><span style="color: #555555;font-style: italic;">&lt;chr&gt;</span><span>    </span><span style="color: #555555;font-style: italic;">&lt;keys&gt;</span><span> 
#&gt; </span><span style="color: #555555;">1</span><span> airlines carrier
#&gt; </span><span style="color: #555555;">2</span><span> airports faa    
#&gt; </span><span style="color: #555555;">3</span><span> planes   tailnum
</span></code></pre>
<p>If an attribute is suitable as a primary key, it can be checked with <code><a href="../reference/enum_pk_candidates.html">dm_enum_pk_candidates()</a></code>. Which columns of the <code>airlines</code> table can serve as a primary key?</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dm</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="../reference/enum_pk_candidates.html">dm_enum_pk_candidates</a></span><span class="op">(</span><span class="va">airports</span><span class="op">)</span></code></pre></div>
<pre class="fansi fansi-output"><code>#&gt; <span style="color: #555555;"># A tibble: 8 x 3</span><span>
#&gt;   columns candidate why                                                    
#&gt;   </span><span style="color: #555555;font-style: italic;">&lt;keys&gt;</span><span>  </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span>     </span><span style="color: #555555;font-style: italic;">&lt;chr&gt;</span><span>                                                  
#&gt; </span><span style="color: #555555;">1</span><span> faa     TRUE      </span><span style="color: #555555;">""</span><span>                                                     
#&gt; </span><span style="color: #555555;">2</span><span> lon     TRUE      </span><span style="color: #555555;">""</span><span>                                                     
#&gt; </span><span style="color: #555555;">3</span><span> alt     FALSE     </span><span style="color: #555555;">"</span><span>has duplicate values: 0, 1, 3, 4, 5, …</span><span style="color: #555555;">"</span><span>               
#&gt; </span><span style="color: #555555;">4</span><span> dst     FALSE     </span><span style="color: #555555;">"</span><span>has duplicate values: A, N, U</span><span style="color: #555555;">"</span><span>                        
#&gt; </span><span style="color: #555555;">5</span><span> lat     FALSE     </span><span style="color: #555555;">"</span><span>has duplicate values: 38.88944, 40.63975</span><span style="color: #555555;">"</span><span>             
#&gt; </span><span style="color: #555555;">6</span><span> name    FALSE     </span><span style="color: #555555;">"</span><span>has duplicate values: All Airports, Capital City Airp…
#&gt; </span><span style="color: #555555;">7</span><span> tz      FALSE     </span><span style="color: #555555;">"</span><span>has duplicate values: -10, -9, -8, -7, -6, …</span><span style="color: #555555;">"</span><span>         
#&gt; </span><span style="color: #555555;">8</span><span> tzone   FALSE     </span><span style="color: #555555;">"</span><span>has missing values, and duplicate values: America/Anc…
</span></code></pre>
<p>Further Reading: The {dm} package offers several functions for dealing with <a href="https://krlmlr.github.io/dm/articles/tech-dm-class.html#pk">primary keys</a>.</p>
</div>
<div id="fk" class="section level2">
<h2 class="hasAnchor">
<a href="#fk" class="anchor" aria-hidden="true"></a>4. Foreign Keys</h2>
<p>The <strong>counterpart of a primary key in one table is the foreign key in another table</strong>. In order to join two tables, the primary key of the first table needs to be available in the second table as well. This second column is called the <em>foreign key</em> (abbreviated with fk).</p>
<p>For example, if you want to link the <code>airlines</code> table to the <code>flights</code> table, the primary key in <code>airlines</code> needs to match the foreign key in <code>flights</code>. This condition is satisfied because the column <code>carrier</code> is present as a primary key in the <code>airlines</code> table as well as a foreign key in the <code>flights</code> table. You can find foreign key candidates with the function <code><a href="../reference/dm_enum_fk_candidates.html">dm_enum_fk_candidates()</a></code>, they are marked with <code>TRUE</code> in the <code>candidate</code> column.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dm</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="../reference/dm_enum_fk_candidates.html">dm_enum_fk_candidates</a></span><span class="op">(</span><span class="va">flights</span>, <span class="va">airlines</span><span class="op">)</span></code></pre></div>
<pre class="fansi fansi-output"><code>#&gt; <span style="color: #555555;"># A tibble: 19 x 3</span><span>
#&gt;    columns      candidate why                                              
#&gt;    </span><span style="color: #555555;font-style: italic;">&lt;keys&gt;</span><span>       </span><span style="color: #555555;font-style: italic;">&lt;lgl&gt;</span><span>     </span><span style="color: #555555;font-style: italic;">&lt;chr&gt;</span><span>                                            
#&gt; </span><span style="color: #555555;"> 1</span><span> carrier      TRUE      </span><span style="color: #555555;">""</span><span>                                               
#&gt; </span><span style="color: #555555;"> 2</span><span> tailnum      FALSE     </span><span style="color: #555555;">"</span><span>11080 entries (98.7%) of `flights$tailnum` not …
#&gt; </span><span style="color: #555555;"> 3</span><span> dest         FALSE     </span><span style="color: #555555;">"</span><span>11227 entries (100%) of `flights$dest` not in `…
#&gt; </span><span style="color: #555555;"> 4</span><span> origin       FALSE     </span><span style="color: #555555;">"</span><span>11227 entries (100%) of `flights$origin` not in…
#&gt; </span><span style="color: #555555;"> 5</span><span> air_time     FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;"> 6</span><span> arr_delay    FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;"> 7</span><span> arr_time     FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;"> 8</span><span> day          FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;"> 9</span><span> dep_delay    FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;">10</span><span> dep_time     FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;">11</span><span> distance     FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;">12</span><span> flight       FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;">13</span><span> hour         FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;">14</span><span> minute       FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;">15</span><span> month        FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;">16</span><span> sched_arr_t… FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;">17</span><span> sched_dep_t… FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;">18</span><span> time_hour    FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
#&gt; </span><span style="color: #555555;">19</span><span> year         FALSE     </span><span style="color: #555555;">"</span><span>Can't join on `x$value` x `y$value` because of …
</span></code></pre>
<p>After finding and assigning foreign keys, get the name of the set foreign key:</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dm</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="../reference/dm_get_fk.html">dm_get_fk</a></span><span class="op">(</span><span class="va">flights</span>, <span class="va">airlines</span><span class="op">)</span>
<span class="co">#&gt; &lt;list_of&lt;character&gt;[1]&gt;</span>
<span class="co">#&gt; [[1]]</span>
<span class="co">#&gt; [1] "carrier"</span></code></pre></div>
<p>Further Reading: All {dm} functions for working with <a href="https://krlmlr.github.io/dm/articles/tech-dm-class.html#foreign-keys">foreign keys</a>.</p>
</div>
<div id="referential-integrity" class="section level2">
<h2 class="hasAnchor">
<a href="#referential-integrity" class="anchor" aria-hidden="true"></a>5. Referential Integrity</h2>
<p>A data set has referential integrity if all relations between tables are valid. That is, every foreign key holds a primary key that is present in the parent table. If a foreign key contains a parent table primary key that has been deleted that row is an orphan row and the database no longer has referential integrity.</p>
<p>{dm} allows checking referential integrity with the <code><a href="../reference/dm_examine_constraints.html">dm_examine_constraints()</a></code> function. The following conditions are checked:</p>
<ul>
<li>All primary key values must be unique.</li>
<li>All primary key values must be set, <code>NA</code> values are not allowed.</li>
<li>Each foreign key value must have a corresponding primary key value.</li>
</ul>
<p>In the example data model, for a substantial share of the flights, detailed information for the corresponding airplane is not available:</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">dm</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="../reference/dm_examine_constraints.html">dm_examine_constraints</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre class="fansi fansi-message"><code>#&gt; <span style="color: #BBBB00;">!</span><span> Unsatisfied constraints:
</span></code></pre>
<pre class="fansi fansi-output"><code>#&gt; <span style="color: #BB0000;">●</span><span> Table `flights`: foreign key dest into table `airports`: 242 entries (2.2%) of `flights$dest` not in `airports$faa`: SJU (187), BQN (28), STT (15), PSE (12)
#&gt; </span><span style="color: #BB0000;">●</span><span> Table `flights`: foreign key tailnum into table `planes`: 1640 entries (14.6%) of `flights$tailnum` not in `planes$tailnum`: N722MQ (27), N725MQ (20), N520MQ (19), N723MQ (19), N508MQ (16), …
</span></code></pre>
<p>Establishing referential integrity is important for providing clean data for analysis or downstream users. See <code><a href="../articles/howto-dm-rows.html">vignette("howto-dm-rows")</a></code> for more information on adding, deleting or updating individual rows, and <code><a href="../articles/tech-dm-zoom.html">vignette("tech-dm-zoom")</a></code> for operations on the data in a data model.</p>
</div>
<div id="normalization" class="section level2">
<h2 class="hasAnchor">
<a href="#normalization" class="anchor" aria-hidden="true"></a>6. Normalization</h2>
<p>Normalization is a technical term that describes the <strong>central design principle of a relational data model</strong>: splitting data into multiple tables.</p>
<p>A normalized data schema consists of several relations (tables) that are linked with attributes (columns). The relations can be joined together by means of <a href="#pk">primary</a> and <a href="#fk">foreign keys</a>. The main goal of normalization is to keep data organization as clean and simple as possible by avoiding redundant data entries.</p>
<p>For example, if you want to change the name of one airport in the <code>nycflights13</code> dataset, you will only need to update a single data value. This principle is sometimes called the <em>single point of truth</em>.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#  Update in one single location...</span>
<span class="va">airlines</span><span class="op">[</span><span class="va">airlines</span><span class="op">$</span><span class="va">carrier</span> <span class="op">==</span> <span class="st">"UA"</span>, <span class="st">"name"</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="st">"United broke my guitar"</span>

<span class="va">airlines</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html" class="external-link">filter</a></span><span class="op">(</span><span class="va">carrier</span> <span class="op">==</span> <span class="st">"UA"</span><span class="op">)</span></code></pre></div>
<pre class="fansi fansi-output"><code>#&gt; <span style="color: #555555;"># A tibble: 1 x 2</span><span>
#&gt;   carrier name                  
#&gt;   </span><span style="color: #555555;font-style: italic;">&lt;chr&gt;</span><span>   </span><span style="color: #555555;font-style: italic;">&lt;chr&gt;</span><span>                 
#&gt; </span><span style="color: #555555;">1</span><span> UA      United broke my guitar
</span></code></pre>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R">
<span class="co"># ...propagates to all related records</span>
<span class="va">flights</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">left_join</a></span><span class="op">(</span><span class="va">airlines</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="va">flight</span>, <span class="va">name</span><span class="op">)</span>
<span class="co">#&gt; Joining, by = "carrier"</span></code></pre></div>
<pre class="fansi fansi-output"><code>#&gt; <span style="color: #555555;"># A tibble: 336,776 x 2</span><span>
#&gt;    flight name                    
#&gt;     </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;chr&gt;</span><span>                   
#&gt; </span><span style="color: #555555;"> 1</span><span>   </span><span style="text-decoration: underline;">1</span><span>545 United broke my guitar  
#&gt; </span><span style="color: #555555;"> 2</span><span>   </span><span style="text-decoration: underline;">1</span><span>714 United broke my guitar  
#&gt; </span><span style="color: #555555;"> 3</span><span>   </span><span style="text-decoration: underline;">1</span><span>141 American Airlines Inc.  
#&gt; </span><span style="color: #555555;"> 4</span><span>    725 JetBlue Airways         
#&gt; </span><span style="color: #555555;"> 5</span><span>    461 Delta Air Lines Inc.    
#&gt; </span><span style="color: #555555;"> 6</span><span>   </span><span style="text-decoration: underline;">1</span><span>696 United broke my guitar  
#&gt; </span><span style="color: #555555;"> 7</span><span>    507 JetBlue Airways         
#&gt; </span><span style="color: #555555;"> 8</span><span>   </span><span style="text-decoration: underline;">5</span><span>708 ExpressJet Airlines Inc.
#&gt; </span><span style="color: #555555;"> 9</span><span>     79 JetBlue Airways         
#&gt; </span><span style="color: #555555;">10</span><span>    301 American Airlines Inc.  
#&gt; </span><span style="color: #555555;"># … with 336,766 more rows</span><span>
</span></code></pre>
<p>Another way to demonstrate normalization is splitting a table into two parts.</p>
<p>Let’s look at the <code>planes</code> table, which consists of 3322 individual tail numbers and corresponding information for the specific airplane, like the year it was manufactured or the average cruising speed.</p>
<p>The function <code><a href="../reference/decompose_table.html">decompose_table()</a></code> extracts two new tables and creates a new key <code>model_id</code>, that links both tables.</p>
<p>This results in a <code>parent_table</code> and a <code>child_table</code> that differ massively in the number of rows:</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">planes</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="../reference/decompose_table.html">decompose_table</a></span><span class="op">(</span><span class="va">model_id</span>, <span class="va">model</span>, <span class="va">manufacturer</span>, <span class="va">type</span>, <span class="va">engines</span>, <span class="va">seats</span>, <span class="va">manufacturer</span>, <span class="va">speed</span><span class="op">)</span></code></pre></div>
<pre class="fansi fansi-output"><code>#&gt; $child_table
#&gt; <span style="color: #555555;"># A tibble: 3,322 x 4</span><span>
#&gt;    tailnum  year engine    model_id
#&gt;    </span><span style="color: #555555;font-style: italic;">&lt;chr&gt;</span><span>   </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;chr&gt;</span><span>        </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span>
#&gt; </span><span style="color: #555555;"> 1</span><span> N10156   </span><span style="text-decoration: underline;">2</span><span>004 Turbo-fan      120
#&gt; </span><span style="color: #555555;"> 2</span><span> N102UW   </span><span style="text-decoration: underline;">1</span><span>998 Turbo-fan       93
#&gt; </span><span style="color: #555555;"> 3</span><span> N103US   </span><span style="text-decoration: underline;">1</span><span>999 Turbo-fan       93
#&gt; </span><span style="color: #555555;"> 4</span><span> N104UW   </span><span style="text-decoration: underline;">1</span><span>999 Turbo-fan       93
#&gt; </span><span style="color: #555555;"> 5</span><span> N10575   </span><span style="text-decoration: underline;">2</span><span>002 Turbo-fan      119
#&gt; </span><span style="color: #555555;"> 6</span><span> N105UW   </span><span style="text-decoration: underline;">1</span><span>999 Turbo-fan       93
#&gt; </span><span style="color: #555555;"> 7</span><span> N107US   </span><span style="text-decoration: underline;">1</span><span>999 Turbo-fan       93
#&gt; </span><span style="color: #555555;"> 8</span><span> N108UW   </span><span style="text-decoration: underline;">1</span><span>999 Turbo-fan       93
#&gt; </span><span style="color: #555555;"> 9</span><span> N109UW   </span><span style="text-decoration: underline;">1</span><span>999 Turbo-fan       93
#&gt; </span><span style="color: #555555;">10</span><span> N110UW   </span><span style="text-decoration: underline;">1</span><span>999 Turbo-fan       93
#&gt; </span><span style="color: #555555;"># … with 3,312 more rows</span><span>
#&gt; 
#&gt; $parent_table
#&gt; </span><span style="color: #555555;"># A tibble: 147 x 7</span><span>
#&gt;    model_id model      manufacturer   type              engines seats speed
#&gt;       </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;chr&gt;</span><span>      </span><span style="color: #555555;font-style: italic;">&lt;chr&gt;</span><span>          </span><span style="color: #555555;font-style: italic;">&lt;chr&gt;</span><span>               </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span> </span><span style="color: #555555;font-style: italic;">&lt;int&gt;</span><span>
#&gt; </span><span style="color: #555555;"> 1</span><span>      120 EMB-145XR  EMBRAER        Fixed wing multi…       2    55    </span><span style="color: #BB0000;">NA</span><span>
#&gt; </span><span style="color: #555555;"> 2</span><span>       93 A320-214   AIRBUS INDUST… Fixed wing multi…       2   182    </span><span style="color: #BB0000;">NA</span><span>
#&gt; </span><span style="color: #555555;"> 3</span><span>      119 EMB-145LR  EMBRAER        Fixed wing multi…       2    55    </span><span style="color: #BB0000;">NA</span><span>
#&gt; </span><span style="color: #555555;"> 4</span><span>       39 737-824    BOEING         Fixed wing multi…       2   149    </span><span style="color: #BB0000;">NA</span><span>
#&gt; </span><span style="color: #555555;"> 5</span><span>       68 767-332    BOEING         Fixed wing multi…       2   330    </span><span style="color: #BB0000;">NA</span><span>
#&gt; </span><span style="color: #555555;"> 6</span><span>       52 757-224    BOEING         Fixed wing multi…       2   178    </span><span style="color: #BB0000;">NA</span><span>
#&gt; </span><span style="color: #555555;"> 7</span><span>       94 A320-214   AIRBUS         Fixed wing multi…       2   182    </span><span style="color: #BB0000;">NA</span><span>
#&gt; </span><span style="color: #555555;"> 8</span><span>      112 CL-600-2D… BOMBARDIER INC Fixed wing multi…       2    95    </span><span style="color: #BB0000;">NA</span><span>
#&gt; </span><span style="color: #555555;"> 9</span><span>       30 737-724    BOEING         Fixed wing multi…       2   149    </span><span style="color: #BB0000;">NA</span><span>
#&gt; </span><span style="color: #555555;">10</span><span>       27 737-524    BOEING         Fixed wing multi…       2   149    </span><span style="color: #BB0000;">NA</span><span>
#&gt; </span><span style="color: #555555;"># … with 137 more rows</span><span>
</span></code></pre>
<p>While <code>child_table</code> contains 3322 unique <code>tailnum</code> rows and therefore consists of 3322 rows, just like the original <code>planes</code> table, the <code>parent_table</code> shrunk to just 147 rows, enough to store all relevant combinations and avoid storing redundant information.</p>
<p>Further Reading: See the <a href="https://simple.wikipedia.org/wiki/Database_normalisation" class="external-link">Simple English Wikipedia article on database normalization</a> for more details.</p>
</div>
<div id="relational-databases" class="section level2">
<h2 class="hasAnchor">
<a href="#relational-databases" class="anchor" aria-hidden="true"></a>7. Relational Databases</h2>
<p>{dm} is built upon relational data models but it is not a database itself. Databases are systems for data management and many of them are constructed as relational databases, e.g. SQLite, MySQL, MSSQL, Postgres. As you can guess from the names of the databases, SQL, short for Structured Querying Language, plays an important role: it was invented for the purpose of querying relational databases.</p>
<p>In production, the data is stored in a relational database and {dm} is used to work with the data.</p>
<p>Therefore, {dm} can copy data <a href="https://krlmlr.github.io/dm/articles/dm.html#copy">from and to databases</a>, and works transparently with both in-memory data and with relational database systems.</p>
<p>For example, let’s create a local SQLite database and copy the <code>dm</code> object to it:</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">con_sqlite</span> <span class="op">&lt;-</span> <span class="fu">DBI</span><span class="fu">::</span><span class="fu"><a href="https://dbi.r-dbi.org/reference/dbConnect.html" class="external-link">dbConnect</a></span><span class="op">(</span><span class="fu">RSQLite</span><span class="fu">::</span><span class="fu"><a href="https://rsqlite.r-dbi.org/reference/SQLite.html" class="external-link">SQLite</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span>
<span class="va">con_sqlite</span>
<span class="co">#&gt; &lt;SQLiteConnection&gt;</span>
<span class="co">#&gt;   Path: </span>
<span class="co">#&gt;   Extensions: TRUE</span>
<span class="fu">DBI</span><span class="fu">::</span><span class="fu"><a href="https://dbi.r-dbi.org/reference/dbListTables.html" class="external-link">dbListTables</a></span><span class="op">(</span><span class="va">con_sqlite</span><span class="op">)</span>
<span class="co">#&gt; character(0)</span>

<span class="fu"><a href="../reference/copy_dm_to.html">copy_dm_to</a></span><span class="op">(</span><span class="va">con_sqlite</span>, <span class="va">dm</span><span class="op">)</span>
<span class="fu">DBI</span><span class="fu">::</span><span class="fu"><a href="https://dbi.r-dbi.org/reference/dbListTables.html" class="external-link">dbListTables</a></span><span class="op">(</span><span class="va">con_sqlite</span><span class="op">)</span>
<span class="co">#&gt; [1] "airlines_2020_08_28_07_13_03_1" "airports_2020_08_28_07_13_03_1"</span>
<span class="co">#&gt; [3] "flights_2020_08_28_07_13_03_1"  "planes_2020_08_28_07_13_03_1"  </span>
<span class="co">#&gt; [5] "sqlite_stat1"                   "sqlite_stat4"                  </span>
<span class="co">#&gt; [7] "weather_2020_08_28_07_13_03_1"</span></code></pre></div>
<p>In the opposite direction, <code>dm</code> can also be populated with data from a DB. Unfortunately, keys currently can be learned only for MSSQL and Postgres, but not for SQLite. Therefore, the dm contains the tables but not the keys:</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/dm_from_src.html">dm_from_src</a></span><span class="op">(</span><span class="va">con_sqlite</span><span class="op">)</span>
<span class="co">#&gt; Keys could not be queried, use `learn_keys = FALSE` to mute this message.</span></code></pre></div>
<pre class="fansi fansi-output"><code>#&gt; <span style="color: #00BB00;">──</span><span> </span><span style="color: #00BB00;">Table source</span><span> </span><span style="color: #00BB00;">───────────────────────────────────────────────────────────</span><span>
#&gt; src:  sqlite 3.35.5 []
#&gt; </span><span style="color: #555555;">──</span><span> </span><span style="color: #555555;">Metadata</span><span> </span><span style="color: #555555;">───────────────────────────────────────────────────────────────</span><span>
#&gt; Tables: `airlines_2020_08_28_07_13_03_1`, `airports_2020_08_28_07_13_03_1`, `flights_2020_08_28_07_13_03_1`, `planes_2020_08_28_07_13_03_1`, `sqlite_stat1`, … (7 total)
#&gt; Columns: 62
#&gt; Primary keys: 0
#&gt; Foreign keys: 0
</span></code></pre>
<p>Remember to terminate the database connection:</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">DBI</span><span class="fu">::</span><span class="fu"><a href="https://dbi.r-dbi.org/reference/dbDisconnect.html" class="external-link">dbDisconnect</a></span><span class="op">(</span><span class="va">con_sqlite</span><span class="op">)</span></code></pre></div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p></p>
<p>Developed by Tobias Schieferdecker, <a href="http://krlmlr.info" class="external-link external-link">Kirill Müller</a>, Darko Bergant, <a href="https://www.energie360.ch/de/" class="external-link external-link"><img src="https://krlmlr.github.io/dm/reference/figures/energie-72.png" height="16"></a>, <a href="https://www.cynkra.com" class="external-link external-link"><img src="https://krlmlr.github.io/dm/reference/figures/cynkra-72.png" height="16"></a>.</p>
</div>

<div class="pkgdown">
  <p></p>
<p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link external-link">pkgdown</a> 1.6.1.9001.</p>
</div>

      </footer>
</div>

  


  

  </body>
</html>
