# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "parent_table", # <build_copy_queries>
  "parent_key_cols", # <build_copy_queries>
  "autoincrement", # <build_copy_queries>
  "name", # <build_copy_queries>
  "col_def", # <build_copy_queries>
  "pk_col", # <build_copy_queries>
  "unique_def", # <build_copy_queries>
  "child_table", # <build_copy_queries>
  "child_fk_cols", # <build_copy_queries>
  "fk_def", # <build_copy_queries>
  "remote_name", # <build_copy_queries>
  "remote_name_unquoted", # <build_copy_queries>
  "index_name", # <build_copy_queries>
  "columns", # <build_copy_queries>
  NULL
))
